enable_audio_bell no

# hide_window_decorations yes
font_family JetbrainsMono Nerd Font Mono
text_composition_strategy legacy
font_size 12

background_opacity 0.98
window_padding_width 4


## KEYBINDS
# Reload kitty config
map ctrl+f>r load_config_file

# Create new window/tab
map ctrl+f>c new_tab

# Close current pane
map ctrl+f>x close_window

# Split vertically 
enabled_layouts tall
map ctrl+f>v launch --location=vsplit 

# Navigate between panes
map ctrl+f>h neighboring_window left
map ctrl+f>l neighboring_window right  
map ctrl+f>k neighboring_window up
map ctrl+f>j neighboring_window down

# Navigate between windows/tabs
map ctrl+f>n next_tab
map ctrl+f>p previous_tab


## THEME
# Jellybeans theme for Kitty terminal

# Special colors
foreground           #e8e8d3
background           #111111
cursor               #b0d0f0
cursor_text_color   #151515
selection_foreground #e8e8d3
selection_background #404040

# Black
color0 #151515
color8 #888888

# Red
color1 #cf6a4c
color9 #902020

# Green
color2  #99ad6a
color10 #70b950

# Yellow
color3  #fad07a
color11 #ffb964

# Blue
color4  #8197bf
color12 #8fbfdc

# Magenta
color5  #c6b6ee
color13 #700089

# Cyan
color6  #668799
color14 #8fbfdc

# White
color7  #e8e8d3
color15 #f0f0f0

# Extended colors
color16 #cf6a4c
color17 #d8ad4c
color18 #1c1c1c
color19 #303030
color20 #636363
color21 #c7c7c7

tab_bar_edge top
tab_title_template "{index}"
tab_bar_min_tabs 2
tab_bar_align center
tab_bar_style separator
tab_separator " | "
tab_activity_symbol *

# Tab colors
active_tab_foreground #000
active_tab_background #eee
inactive_tab_foreground #888
inactive_tab_background #111111
