linux_display_server wayland
font_family Lilex
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.5
disable_ligatures never
cursor_shape beam
scrollback_lines 10000
repaint_delay 6
sync_to_monitor yes
confirm_os_window_close 0
enable_audio_bell no

#window
window_padding_width 4
#background_opacity  0.98

# --- Hardcoded Palette ---
background            #151515
foreground            #e1e1e1

cursor                #e1e1e1
selection_background  #5e5e5e
selection_foreground  #e1e1e1

color0                #202020
color8                #555555

color1                #ac4142
color9                #b07777

color2                #9a9a7a
color10               #aaa88a

color3                #f4bf75
color11               #ffdead

color4                #8a8a8a
color12               #9a9a9a

color5                #aa759f
color13               #cf75bc

color6                #7a8a8a
color14               #8a9a9a

color7                #d0d0d0
color15               #e1e1e1
