# Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.

client.focused #9b8d7f #9b8d7f #000000 #9b8d7f #9b8d7f
client.focused_inactive #202020 #202020 #9b8d7f #202020 #202020
client.unfocused #202020 #202020 #9b8d7f #202020 #202020

bar {
    # swaybar_command swaybar
    swaybar_command waybar

    # When the status_command prints a new line to stdout, swaybar updates.
    # The default just shows the current date and time.
    status_command while date +'%Y-%m-%d :: %X'; do sleep 1; done

    #position top
    separator_symbol "::"
    colors {
        background #222222
            statusline #9b8d7f
            separator #9b8d7f

            focused_workspace #9b8d7f #9b8d7f #222222
            inactive_workspace #222222 #222222 #9b8d7f
            active_workspace #222222 #222222 #9b8d7f
            urgent_workspace #222222 #222222 #9b8d7f
            binding_mode #222222 #222222 #9b8d7f
    }
    font pango:Iosevka Term 12
    tray_output HDMI-A-1
}
