# True color goodness #
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g status-style 'fg=#8ec07c'

# Bottom Bar #
set-option -g status-position bottom
set-option -g status-justify centre

set-option -g status-right '#(echo Device: ) #(uname) #(date)'
set-option -g status-left-length 20
set-option -g status-left '#(echo "Session: ")#S'

# remap prefix from 'C-b' to 'C-f' #
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# Enable mouse mode (clickable windows, panes, resizable panes) #
set -g mouse on

# switch panes using Alt-arrow without prefix #
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# split panes using | and - #
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# don't rename windows automatically #
set-option -g allow-rename off

#faster escape in nvim #
set -s escape-time 0
